{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [],
   "source": [
    "import csv\n",
    "import json\n",
    "import sys\n",
    "import numpy as np\n",
    "import pandas as pd\n",
    "import random\n",
    "from tqdm import tqdm\n",
    "\n",
    "projects = ['commons-imaging-1.0-alpha3-src', 'spark', 'commons-lang3-3.12.0-src', 'http-request', 'commons-geometry-1.0-src', 'springside4', 'commons-jexl3-3.2.1-src', 'joda-time', 'async-http-client', 'JSON-java', 'bcel-6.5.0-src', 'commons-weaver-2.0-src', 'commons-numbers-1.0-src', 'commons-collections4-4.4-src', 'jsoup', 'commons-jcs3-3.1-src', 'commons-validator-1.7', 'commons-net-3.8.0', 'commons-beanutils-1.9.4', 'commons-pool2-2.11.1-src', 'commons-rng-1.4-src', 'commons-configuration2-2.8.0-src', 'commons-vfs-2.9.0', 'scribejava', 'commons-dbutils-1.7']\n",
    "# Defining functions\n",
    "calc_f1 = lambda df: np.round((2*df['tp'])/(2*df['tp']+df['fp']+df['fn']), 4)\n",
    "calc_pass_accuracy = lambda df: np.round((df['tp'])/(df['tp']+df['fn']), 4)\n",
    "calc_fail_accuracy = lambda df: np.round((df['tn'])/(df['tn']+df['fp']), 4)\n",
    "calc_accuracy = lambda df: np.round((df['tp']+df['tn'])/df['N'], 4)\n",
    "calc_pass_rate = lambda df: np.round((df['tp']+df['fn'])/df['N'], 4)\n",
    "calc_fail_rate = lambda df: np.round((df['tn']+df['fp'])/df['N'], 4)\n",
    "\n",
    "def combine_project_data(project):\n",
    "    path = './real_data_gen/fold0'\n",
    "\n",
    "    # Combining all the test_stats.csv files into one for subsequent analysis\n",
    "    open(f\"{path}/test_stats.csv\", 'w').close()\n",
    "\n",
    "    with open(f\"{path}/test_stats.csv\", \"ab\") as fout:\n",
    "        # First file:\n",
    "        with open(f\"{path}/{projects[0]}/test_stats.csv\", \"rb\") as f:\n",
    "            fout.writelines(f)\n",
    "\n",
    "        # Now the rest:\n",
    "        for project in projects[1:]:\n",
    "            with open(f\"{path}/{project}/test_stats.csv\", \"rb\") as f:\n",
    "                next(f) # Skip the header, portably\n",
    "                fout.writelines(f)\n",
    "                \n",
    "def run_coin_flip_test(project_data, pass_rate):\n",
    "    df = project_data.copy()\n",
    "    num_rows = len(df)\n",
    "    coin_accuracy = []\n",
    "    coin_f1 = []\n",
    "\n",
    "    iterations = int(np.ceil(10000/num_rows))\n",
    "\n",
    "    for i in range(iterations):\n",
    "        coin_simulation = [1 if (random.random() < pass_rate) else 0 for i in range(num_rows)]\n",
    "        df['coin_simulation'] = coin_simulation\n",
    "        coin_tp = 0\n",
    "        coin_fn = 0\n",
    "        coin_tn = 0\n",
    "        coin_fp = 0\n",
    "\n",
    "        for i in range(num_rows):\n",
    "\n",
    "            # row[0] is the prediction, Row[1] is the actual\n",
    "            # predicted and actual pass\n",
    "            if df.loc[i, 'Actual Label'] == 1 and df.loc[i, 'coin_simulation'] == 1:\n",
    "                coin_tp += 1\n",
    "            # predicted fail and actual pass\n",
    "            elif df.loc[i, 'Actual Label'] == 1 and df.loc[i, 'coin_simulation'] == 0:\n",
    "                coin_fn += 1\n",
    "            # predicted and actual fail\n",
    "            elif df.loc[i, 'Actual Label'] == 0 and df.loc[i, 'coin_simulation'] == 0:\n",
    "                coin_tn += 1\n",
    "            # predicted pass and actual fail\n",
    "            elif df.loc[i, 'Actual Label'] == 0 and df.loc[i, 'coin_simulation'] == 1:\n",
    "                coin_fp += 1\n",
    "\n",
    "        coin_accuracy.append((coin_tp+coin_tn)/num_rows)\n",
    "        coin_f1.append((2*coin_tp)/(2*coin_tp+coin_fp+coin_fn))\n",
    "\n",
    "    average_coin_accuracy = np.round(np.mean(coin_accuracy), 4)\n",
    "    average_coin_f1 = np.round(np.mean(coin_f1), 4)\n",
    "    return average_coin_accuracy, average_coin_f1\n",
    "\n",
    "# Intaking data\n",
    "# projects = sys.argv[1].split(sep='*')\n",
    "# projects = '*'.join(projects).split(sep='*')\n",
    "\n",
    "def generate_vocab_data(temp, threshold, project):\n",
    "    columns_vocab_summary = ['project', 'total_C_tokens', 'total_C_fail', 'out_vocab_C_ratio', 'total_T_tokens', 'total_T_fail', 'out_vocab_T_ratio', 'out_vocab_combined_ratio']\n",
    "    temp = temp[(temp['project']==project) & (temp['out_vocab_ratio'] <= threshold)]\n",
    "\n",
    "    valid_ind = temp.index.tolist()\n",
    "\n",
    "    total_C_tokens = np.sum(temp['C_tokens'])\n",
    "    total_T_tokens = np.sum(temp['T_tokens'])\n",
    "    total_T_fail = np.sum(temp['T_tokens_fail'])\n",
    "    total_C_fail = np.sum(temp['C_tokens_fail'])\n",
    "\n",
    "    if (total_C_tokens + total_T_tokens) == 0:\n",
    "        return None, None\n",
    "\n",
    "    out_vocab_C_ratio = np.round(total_C_fail / total_C_tokens, 2)\n",
    "    out_vocab_T_ratio = np.round(total_T_fail / total_T_tokens, 2)\n",
    "    out_vocab_combined_ratio = np.round((total_T_fail + total_C_fail) / (total_C_tokens + total_T_tokens), 2)\n",
    "    # print(f'Error with {project}')\n",
    "    # print(f'total_C_tokens: {total_C_tokens}')\n",
    "    # print(f'total_T_tokens: {total_T_tokens}')\n",
    "    # print(f'total_T_fail: {total_T_fail}')\n",
    "    # print(f'total_C_fail: {total_C_fail}')\n",
    "\n",
    "    data = [project, total_C_tokens, total_C_fail, out_vocab_C_ratio, total_T_tokens, total_T_fail, out_vocab_T_ratio, out_vocab_combined_ratio]\n",
    "\n",
    "    temp_df = pd.DataFrame(data).T\n",
    "    temp_df.columns = columns_vocab_summary\n",
    "\n",
    "    return temp_df, valid_ind\n",
    "\n",
    "def generate_results_data(project, path, valid_ind):\n",
    "    results_project = {}\n",
    "    project_data = pd.read_csv(f\"{path}/{project}/test_stats.csv\")\n",
    "    print(project_data.index.tolist())\n",
    "    project_data = project_data.reindex(valid_ind)\n",
    "\n",
    "    num_rows = len(project_data)\n",
    "    tp = 0\n",
    "    fp = 0\n",
    "    tn = 0\n",
    "    fn = 0\n",
    "    for i in range(num_rows):\n",
    "\n",
    "        # row[0] is the prediction, Row[1] is the actual\n",
    "        # predicted and actual pass\n",
    "        if project_data.loc[i, 'Actual Label'] == 1 and project_data.loc[i, 'Predicted Label'] == 1:\n",
    "            tp += 1\n",
    "        # predicted fail and actual pass\n",
    "        elif project_data.loc[i, 'Actual Label'] == 1 and project_data.loc[i, 'Predicted Label'] == 0:\n",
    "            fn += 1\n",
    "        # predicted and actual fail\n",
    "        elif project_data.loc[i, 'Actual Label'] == 0 and project_data.loc[i, 'Predicted Label'] == 0:\n",
    "            tn += 1\n",
    "        # predicted pass and actual fail\n",
    "        elif project_data.loc[i, 'Actual Label'] == 0 and project_data.loc[i, 'Predicted Label'] == 1:\n",
    "            fp += 1\n",
    "\n",
    "    results_project['N'] = num_rows\n",
    "    results_project['tp'] = tp\n",
    "    results_project['fn'] = fn\n",
    "    results_project['tn'] = tn\n",
    "    results_project['fp'] = fp\n",
    "\n",
    "    # Dataset stats  \n",
    "    results_project['accuracy'] = calc_accuracy(results_project)\n",
    "    results_project['f1'] = calc_f1(results_project)\n",
    "    results_project['pass_accuracy'] = calc_pass_accuracy(results_project)\n",
    "    results_project['fail_accuracy'] = calc_fail_accuracy(results_project)\n",
    "\n",
    "    results_project['pass_rate'] = calc_pass_rate(results_project)\n",
    "    results_project['fail_rate'] = calc_fail_rate(results_project)\n",
    "\n",
    "    # Coin flip test    \n",
    "    results_project['coin_accuracy'], results_project['coin_f1'] = run_coin_flip_test(project_data, results_project['pass_rate'])\n",
    "    results_project['accuracy_improvement'] = np.round(results_project['accuracy'] - results_project['coin_accuracy'], 4)\n",
    "\n",
    "    return results_project\n",
    "\n",
    "def calculate_overall_metrics(projects=projects, thresholds = [1.0, .50, .25, .10, .05]):\n",
    "\n",
    "    # project_count = len(projects)\n",
    "    path = './real_data_gen/fold0'\n",
    "\n",
    "    # Vocab analysis\n",
    "    print('Creating final results for each threshold value...')\n",
    "    vocab = pd.read_json(f'{path}/out-of-vocab.json', orient='index')\n",
    "    vocab['out_vocab_ratio'] = np.round((vocab['C_tokens_fail'] + vocab['T_tokens_fail']) / (vocab['C_tokens'] + vocab['T_tokens']), 2)\n",
    "    columns_vocab_summary = ['project', 'total_C_tokens', 'total_C_fail', 'out_vocab_C_ratio', 'total_T_tokens', 'total_T_fail', 'out_vocab_T_ratio', 'out_vocab_combined_ratio']\n",
    "\n",
    "    for threshold in tqdm(thresholds):\n",
    "        threshold_string = \"{:.2f}\".format(threshold).replace('.', '')[1:] if threshold != 1.0 else 'all'\n",
    "        # Initialize data objects\n",
    "        vocab_summary = pd.DataFrame(columns=columns_vocab_summary)\n",
    "        results_dict = {}\n",
    "        for project in tqdm(projects, leave=False):\n",
    "            # Vocab analysis\n",
    "            temp_df, valid_ind = generate_vocab_data(vocab, threshold, project)\n",
    "            if temp_df is None:\n",
    "                continue\n",
    "            vocab_summary = pd.concat([vocab_summary, temp_df], ignore_index=True)\n",
    "            # Results analysis\n",
    "            results_project = generate_results_data(project, path, valid_ind)\n",
    "            results_dict[project] = results_project\n",
    "\n",
    "        vocab_summary.loc['all', 'project'] = 'all'\n",
    "        vocab_summary.loc['all', 'total_C_tokens'] = np.sum(vocab_summary['total_C_tokens'])\n",
    "        vocab_summary.loc['all', 'total_C_fail'] = np.sum(vocab_summary['total_C_fail'])\n",
    "        vocab_summary.loc['all', 'out_vocab_C_ratio'] = np.round(vocab_summary.loc['all', 'total_C_fail'] / vocab_summary.loc['all', 'total_C_tokens'], 2)\n",
    "        vocab_summary.loc['all', 'total_T_tokens'] = np.sum(vocab_summary['total_T_tokens'])\n",
    "        vocab_summary.loc['all', 'total_T_fail'] = np.sum(vocab_summary['total_T_fail'])\n",
    "        vocab_summary.loc['all', 'out_vocab_T_ratio'] = np.round(vocab_summary.loc['all', 'total_T_fail'] / vocab_summary.loc['all', 'total_T_tokens'], 2)\n",
    "        vocab_summary.loc['all', 'out_vocab_combined_ratio'] = np.round((vocab_summary.loc['all', 'total_T_fail'] + vocab_summary.loc['all', 'total_C_fail']) / (vocab_summary.loc['all', 'total_C_tokens'] + vocab_summary.loc['all', 'total_T_tokens']), 2)\n",
    "\n",
    "\n",
    "        sorting = pd.DataFrame(results_dict).T\n",
    "        sorting.index.name = 'project'\n",
    "        sorting = sorting.reset_index().merge(vocab_summary[['project','out_vocab_C_ratio','out_vocab_T_ratio', 'out_vocab_combined_ratio']], left_on='project', right_on='project', how='outer').set_index('project')\n",
    "        sorting.sort_values(by=['accuracy_improvement'], ascending=False, inplace=True)\n",
    "\n",
    "        # Adding totals\n",
    "        sorting.loc['all', 'N'] = np.sum(sorting['N'])\n",
    "        sorting.loc['all', 'tp'] = np.sum(sorting['tp'])\n",
    "        sorting.loc['all', 'fn'] = np.sum(sorting['fn'])\n",
    "        sorting.loc['all', 'tn'] = np.sum(sorting['tn'])\n",
    "        sorting.loc['all', 'fp'] = np.sum(sorting['fp'])\n",
    "        sorting.loc['all', 'accuracy'] = calc_accuracy(sorting.loc['all'])\n",
    "        sorting.loc['all', 'f1'] = calc_f1(sorting.loc['all'])\n",
    "        sorting.loc['all', 'pass_accuracy'] = calc_pass_accuracy(sorting.loc['all'])\n",
    "        sorting.loc['all', 'fail_accuracy'] = calc_fail_accuracy(sorting.loc['all'])\n",
    "        sorting.loc['all', 'pass_rate'] = calc_pass_rate(sorting.loc['all'])\n",
    "        sorting.loc['all', 'fail_rate'] = calc_fail_rate(sorting.loc['all'])\n",
    "\n",
    "        overall_results_df = pd.read_csv(f\"{path}/test_stats.csv\")\n",
    "        sorting.loc['all', 'coin_accuracy'], sorting.loc['all', 'coin_f1'] = run_coin_flip_test(overall_results_df, sorting.loc['all', 'pass_rate'])\n",
    "        sorting.loc['all', 'accuracy_improvement'] = np.round(sorting.loc['all', 'accuracy'] - sorting.loc['all', 'coin_accuracy'], 4)\n",
    "\n",
    "        sorting = sorting.astype({'fn': 'int32', 'tn': 'int32', 'fp': 'int32', 'tp': 'int32', 'N': 'int32'})\n",
    "\n",
    "\n",
    "        sorting.to_csv(f\"{path}/project_stats_{threshold_string}.csv\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Creating final results for each threshold value...\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/home/anrath/miniconda3/envs/seer/lib/python3.6/site-packages/ipykernel_launcher.py:31: RuntimeWarning: invalid value encountered in long_scalars\n",
      "/home/anrath/miniconda3/envs/seer/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in long_scalars\n",
      "/home/anrath/miniconda3/envs/seer/lib/python3.6/site-packages/ipykernel_launcher.py:33: RuntimeWarning: invalid value encountered in long_scalars\n",
      "/home/anrath/miniconda3/envs/seer/lib/python3.6/site-packages/ipykernel_launcher.py:31: RuntimeWarning: invalid value encountered in long_scalars\n",
      "/home/anrath/miniconda3/envs/seer/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in long_scalars\n",
      "/home/anrath/miniconda3/envs/seer/lib/python3.6/site-packages/ipykernel_launcher.py:33: RuntimeWarning: invalid value encountered in long_scalars\n",
      "/home/anrath/miniconda3/envs/seer/lib/python3.6/site-packages/ipykernel_launcher.py:31: RuntimeWarning: invalid value encountered in long_scalars\n",
      "/home/anrath/miniconda3/envs/seer/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in long_scalars\n",
      "/home/anrath/miniconda3/envs/seer/lib/python3.6/site-packages/ipykernel_launcher.py:33: RuntimeWarning: invalid value encountered in long_scalars\n",
      "/home/anrath/miniconda3/envs/seer/lib/python3.6/site-packages/ipykernel_launcher.py:31: RuntimeWarning: invalid value encountered in long_scalars\n",
      "/home/anrath/miniconda3/envs/seer/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in long_scalars\n",
      "/home/anrath/miniconda3/envs/seer/lib/python3.6/site-packages/ipykernel_launcher.py:33: RuntimeWarning: invalid value encountered in long_scalars\n",
      "/home/anrath/miniconda3/envs/seer/lib/python3.6/site-packages/ipykernel_launcher.py:31: RuntimeWarning: invalid value encountered in long_scalars\n",
      "/home/anrath/miniconda3/envs/seer/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in long_scalars\n",
      "/home/anrath/miniconda3/envs/seer/lib/python3.6/site-packages/ipykernel_launcher.py:33: RuntimeWarning: invalid value encountered in long_scalars\n",
      "/home/anrath/miniconda3/envs/seer/lib/python3.6/site-packages/ipykernel_launcher.py:31: RuntimeWarning: invalid value encountered in long_scalars\n",
      "/home/anrath/miniconda3/envs/seer/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in long_scalars\n",
      "/home/anrath/miniconda3/envs/seer/lib/python3.6/site-packages/ipykernel_launcher.py:33: RuntimeWarning: invalid value encountered in long_scalars\n",
      "/home/anrath/miniconda3/envs/seer/lib/python3.6/site-packages/ipykernel_launcher.py:31: RuntimeWarning: invalid value encountered in long_scalars\n",
      "/home/anrath/miniconda3/envs/seer/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in long_scalars\n",
      "/home/anrath/miniconda3/envs/seer/lib/python3.6/site-packages/ipykernel_launcher.py:33: RuntimeWarning: invalid value encountered in long_scalars\n",
      "/home/anrath/miniconda3/envs/seer/lib/python3.6/site-packages/ipykernel_launcher.py:31: RuntimeWarning: invalid value encountered in long_scalars\n",
      "/home/anrath/miniconda3/envs/seer/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in long_scalars\n",
      "/home/anrath/miniconda3/envs/seer/lib/python3.6/site-packages/ipykernel_launcher.py:33: RuntimeWarning: invalid value encountered in long_scalars\n",
      "/home/anrath/miniconda3/envs/seer/lib/python3.6/site-packages/ipykernel_launcher.py:31: RuntimeWarning: invalid value encountered in long_scalars\n",
      "/home/anrath/miniconda3/envs/seer/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in long_scalars\n",
      "/home/anrath/miniconda3/envs/seer/lib/python3.6/site-packages/ipykernel_launcher.py:33: RuntimeWarning: invalid value encountered in long_scalars\n",
      "/home/anrath/miniconda3/envs/seer/lib/python3.6/site-packages/ipykernel_launcher.py:31: RuntimeWarning: invalid value encountered in long_scalars\n",
      "/home/anrath/miniconda3/envs/seer/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in long_scalars\n",
      "/home/anrath/miniconda3/envs/seer/lib/python3.6/site-packages/ipykernel_launcher.py:33: RuntimeWarning: invalid value encountered in long_scalars\n",
      "/home/anrath/miniconda3/envs/seer/lib/python3.6/site-packages/ipykernel_launcher.py:31: RuntimeWarning: invalid value encountered in long_scalars\n",
      "/home/anrath/miniconda3/envs/seer/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in long_scalars\n",
      "/home/anrath/miniconda3/envs/seer/lib/python3.6/site-packages/ipykernel_launcher.py:33: RuntimeWarning: invalid value encountered in long_scalars\n",
      "/home/anrath/miniconda3/envs/seer/lib/python3.6/site-packages/ipykernel_launcher.py:31: RuntimeWarning: invalid value encountered in long_scalars\n",
      "/home/anrath/miniconda3/envs/seer/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in long_scalars\n",
      "/home/anrath/miniconda3/envs/seer/lib/python3.6/site-packages/ipykernel_launcher.py:33: RuntimeWarning: invalid value encountered in long_scalars\n",
      "/home/anrath/miniconda3/envs/seer/lib/python3.6/site-packages/ipykernel_launcher.py:31: RuntimeWarning: invalid value encountered in long_scalars\n",
      "/home/anrath/miniconda3/envs/seer/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in long_scalars\n",
      "/home/anrath/miniconda3/envs/seer/lib/python3.6/site-packages/ipykernel_launcher.py:33: RuntimeWarning: invalid value encountered in long_scalars\n",
      "/home/anrath/miniconda3/envs/seer/lib/python3.6/site-packages/ipykernel_launcher.py:31: RuntimeWarning: invalid value encountered in long_scalars\n",
      "/home/anrath/miniconda3/envs/seer/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in long_scalars\n",
      "/home/anrath/miniconda3/envs/seer/lib/python3.6/site-packages/ipykernel_launcher.py:33: RuntimeWarning: invalid value encountered in long_scalars\n",
      "/home/anrath/miniconda3/envs/seer/lib/python3.6/site-packages/ipykernel_launcher.py:31: RuntimeWarning: invalid value encountered in long_scalars\n",
      "/home/anrath/miniconda3/envs/seer/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in long_scalars\n",
      "/home/anrath/miniconda3/envs/seer/lib/python3.6/site-packages/ipykernel_launcher.py:33: RuntimeWarning: invalid value encountered in long_scalars\n",
      "/home/anrath/miniconda3/envs/seer/lib/python3.6/site-packages/ipykernel_launcher.py:31: RuntimeWarning: invalid value encountered in long_scalars\n",
      "/home/anrath/miniconda3/envs/seer/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in long_scalars\n",
      "/home/anrath/miniconda3/envs/seer/lib/python3.6/site-packages/ipykernel_launcher.py:33: RuntimeWarning: invalid value encountered in long_scalars\n",
      "/home/anrath/miniconda3/envs/seer/lib/python3.6/site-packages/ipykernel_launcher.py:31: RuntimeWarning: invalid value encountered in long_scalars\n",
      "/home/anrath/miniconda3/envs/seer/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in long_scalars\n",
      "/home/anrath/miniconda3/envs/seer/lib/python3.6/site-packages/ipykernel_launcher.py:33: RuntimeWarning: invalid value encountered in long_scalars\n",
      "/home/anrath/miniconda3/envs/seer/lib/python3.6/site-packages/ipykernel_launcher.py:31: RuntimeWarning: invalid value encountered in long_scalars\n",
      "/home/anrath/miniconda3/envs/seer/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in long_scalars\n",
      "/home/anrath/miniconda3/envs/seer/lib/python3.6/site-packages/ipykernel_launcher.py:33: RuntimeWarning: invalid value encountered in long_scalars\n",
      "/home/anrath/miniconda3/envs/seer/lib/python3.6/site-packages/ipykernel_launcher.py:31: RuntimeWarning: invalid value encountered in long_scalars\n",
      "/home/anrath/miniconda3/envs/seer/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in long_scalars\n",
      "/home/anrath/miniconda3/envs/seer/lib/python3.6/site-packages/ipykernel_launcher.py:33: RuntimeWarning: invalid value encountered in long_scalars\n",
      "/home/anrath/miniconda3/envs/seer/lib/python3.6/site-packages/ipykernel_launcher.py:31: RuntimeWarning: invalid value encountered in long_scalars\n",
      "/home/anrath/miniconda3/envs/seer/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in long_scalars\n",
      "/home/anrath/miniconda3/envs/seer/lib/python3.6/site-packages/ipykernel_launcher.py:33: RuntimeWarning: invalid value encountered in long_scalars\n",
      "/home/anrath/miniconda3/envs/seer/lib/python3.6/site-packages/ipykernel_launcher.py:31: RuntimeWarning: invalid value encountered in long_scalars\n",
      "/home/anrath/miniconda3/envs/seer/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in long_scalars\n",
      "/home/anrath/miniconda3/envs/seer/lib/python3.6/site-packages/ipykernel_launcher.py:33: RuntimeWarning: invalid value encountered in long_scalars\n",
      "/home/anrath/miniconda3/envs/seer/lib/python3.6/site-packages/ipykernel_launcher.py:31: RuntimeWarning: invalid value encountered in long_scalars\n",
      "/home/anrath/miniconda3/envs/seer/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in long_scalars\n",
      "/home/anrath/miniconda3/envs/seer/lib/python3.6/site-packages/ipykernel_launcher.py:33: RuntimeWarning: invalid value encountered in long_scalars\n",
      "/home/anrath/miniconda3/envs/seer/lib/python3.6/site-packages/ipykernel_launcher.py:31: RuntimeWarning: invalid value encountered in long_scalars\n",
      "/home/anrath/miniconda3/envs/seer/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in long_scalars\n",
      "/home/anrath/miniconda3/envs/seer/lib/python3.6/site-packages/ipykernel_launcher.py:33: RuntimeWarning: invalid value encountered in long_scalars\n",
      "/home/anrath/miniconda3/envs/seer/lib/python3.6/site-packages/ipykernel_launcher.py:31: RuntimeWarning: invalid value encountered in long_scalars\n",
      "/home/anrath/miniconda3/envs/seer/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in long_scalars\n",
      "/home/anrath/miniconda3/envs/seer/lib/python3.6/site-packages/ipykernel_launcher.py:33: RuntimeWarning: invalid value encountered in long_scalars\n",
      "/home/anrath/miniconda3/envs/seer/lib/python3.6/site-packages/ipykernel_launcher.py:31: RuntimeWarning: invalid value encountered in long_scalars\n",
      "/home/anrath/miniconda3/envs/seer/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in long_scalars\n",
      "/home/anrath/miniconda3/envs/seer/lib/python3.6/site-packages/ipykernel_launcher.py:33: RuntimeWarning: invalid value encountered in long_scalars\n",
      "/home/anrath/miniconda3/envs/seer/lib/python3.6/site-packages/ipykernel_launcher.py:31: RuntimeWarning: invalid value encountered in long_scalars\n",
      "/home/anrath/miniconda3/envs/seer/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in long_scalars\n",
      "/home/anrath/miniconda3/envs/seer/lib/python3.6/site-packages/ipykernel_launcher.py:33: RuntimeWarning: invalid value encountered in long_scalars\n",
      "/home/anrath/miniconda3/envs/seer/lib/python3.6/site-packages/ipykernel_launcher.py:31: RuntimeWarning: invalid value encountered in long_scalars\n",
      "/home/anrath/miniconda3/envs/seer/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in long_scalars\n",
      "/home/anrath/miniconda3/envs/seer/lib/python3.6/site-packages/ipykernel_launcher.py:33: RuntimeWarning: invalid value encountered in long_scalars\n",
      "/home/anrath/miniconda3/envs/seer/lib/python3.6/site-packages/ipykernel_launcher.py:31: RuntimeWarning: invalid value encountered in long_scalars\n",
      "/home/anrath/miniconda3/envs/seer/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in long_scalars\n",
      "/home/anrath/miniconda3/envs/seer/lib/python3.6/site-packages/ipykernel_launcher.py:33: RuntimeWarning: invalid value encountered in long_scalars\n",
      "/home/anrath/miniconda3/envs/seer/lib/python3.6/site-packages/ipykernel_launcher.py:31: RuntimeWarning: invalid value encountered in long_scalars\n",
      "/home/anrath/miniconda3/envs/seer/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in long_scalars\n",
      "/home/anrath/miniconda3/envs/seer/lib/python3.6/site-packages/ipykernel_launcher.py:33: RuntimeWarning: invalid value encountered in long_scalars\n",
      "/home/anrath/miniconda3/envs/seer/lib/python3.6/site-packages/ipykernel_launcher.py:31: RuntimeWarning: invalid value encountered in long_scalars\n",
      "/home/anrath/miniconda3/envs/seer/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in long_scalars\n",
      "/home/anrath/miniconda3/envs/seer/lib/python3.6/site-packages/ipykernel_launcher.py:33: RuntimeWarning: invalid value encountered in long_scalars\n",
      "/home/anrath/miniconda3/envs/seer/lib/python3.6/site-packages/ipykernel_launcher.py:31: RuntimeWarning: invalid value encountered in long_scalars\n",
      "/home/anrath/miniconda3/envs/seer/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in long_scalars\n",
      "/home/anrath/miniconda3/envs/seer/lib/python3.6/site-packages/ipykernel_launcher.py:33: RuntimeWarning: invalid value encountered in long_scalars\n",
      "/home/anrath/miniconda3/envs/seer/lib/python3.6/site-packages/ipykernel_launcher.py:31: RuntimeWarning: invalid value encountered in long_scalars\n",
      "/home/anrath/miniconda3/envs/seer/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in long_scalars\n",
      "/home/anrath/miniconda3/envs/seer/lib/python3.6/site-packages/ipykernel_launcher.py:33: RuntimeWarning: invalid value encountered in long_scalars\n"
     ]
    }
   ],
   "source": [
    "projects=projects\n",
    "thresholds = [1.0, .50, .25, .10, .05]\n",
    "\n",
    "# project_count = len(projects)\n",
    "path = './real_data_gen/fold0'\n",
    "\n",
    "# Vocab analysis\n",
    "print('Creating final results for each threshold value...')\n",
    "vocab = pd.read_json(f'{path}/out-of-vocab.json', orient='index')\n",
    "vocab['out_vocab_ratio'] = np.round((vocab['C_tokens_fail'] + vocab['T_tokens_fail']) / (vocab['C_tokens'] + vocab['T_tokens']), 2)\n",
    "columns_vocab_summary = ['project', 'total_C_tokens', 'total_C_fail', 'out_vocab_C_ratio', 'total_T_tokens', 'total_T_fail', 'out_vocab_T_ratio', 'out_vocab_combined_ratio']\n",
    "\n",
    "for threshold in thresholds:\n",
    "    threshold_string = \"{:.2f}\".format(threshold).replace('.', '')[1:] if threshold != 1.0 else 'all'\n",
    "    # Initialize data objects\n",
    "    vocab_summary = pd.DataFrame(columns=columns_vocab_summary)\n",
    "    results_dict = {}\n",
    "    for project in projects:\n",
    "        # Vocab analysis\n",
    "        columns_vocab_summary = ['project', 'total_C_tokens', 'total_C_fail', 'out_vocab_C_ratio', 'total_T_tokens', 'total_T_fail', 'out_vocab_T_ratio', 'out_vocab_combined_ratio']\n",
    "        temp = vocab.copy()\n",
    "        temp = temp[(temp['project']==project) & (temp['out_vocab_ratio'] <= threshold)]\n",
    "\n",
    "        valid_ind = temp.index.tolist()\n",
    "\n",
    "        total_C_tokens = np.sum(temp['C_tokens'])\n",
    "        total_T_tokens = np.sum(temp['T_tokens'])\n",
    "        total_T_fail = np.sum(temp['T_tokens_fail'])\n",
    "        total_C_fail = np.sum(temp['C_tokens_fail'])\n",
    "\n",
    "        if (total_C_tokens + total_T_tokens) == 0:\n",
    "            continue\n",
    "\n",
    "        out_vocab_C_ratio = np.round(total_C_fail / total_C_tokens, 2)\n",
    "        out_vocab_T_ratio = np.round(total_T_fail / total_T_tokens, 2)\n",
    "        out_vocab_combined_ratio = np.round((total_T_fail + total_C_fail) / (total_C_tokens + total_T_tokens), 2)\n",
    "\n",
    "        data = [project, total_C_tokens, total_C_fail, out_vocab_C_ratio, total_T_tokens, total_T_fail, out_vocab_T_ratio, out_vocab_combined_ratio]\n",
    "\n",
    "        temp_df = pd.DataFrame(data).T\n",
    "        temp_df.columns = columns_vocab_summary\n",
    "\n",
    "        # vocab_summary = pd.concat([vocab_summary, temp_df], ignore_index=True)\n",
    "        # Results analysis\n",
    "        # results_project = generate_results_data(project, path, valid_ind)\n",
    "        # results_dict[project] = results_project\n",
    "        project_data = pd.read_csv(f\"{path}/{project}/test_stats.csv\")\n",
    "        project_data = project_data.reindex(valid_ind)\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "seer",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.6.13"
  },
  "orig_nbformat": 4
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
