Traceback (most recent call last):
  File "./learning/test.py", line 84, in <module>
    test(args)
  File "./learning/test.py", line 42, in test
    out = model(code, test, "", phase=2)
  File "/u/kl5sq/.conda/envs/seer/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/u/kl5sq/masters/SEER/models/joint_embedder.py", line 72, in forward
    out = torch.relu(self.fc_1(code_test_repr))
  File "/u/kl5sq/.conda/envs/seer/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/u/kl5sq/.conda/envs/seer/lib/python3.6/site-packages/torch/nn/modules/linear.py", line 103, in forward
    return F.linear(input, self.weight, self.bias)
  File "/u/kl5sq/.conda/envs/seer/lib/python3.6/site-packages/torch/nn/functional.py", line 1848, in linear
    return torch._C._nn.linear(input, weight, bias)
RuntimeError: mat1 and mat2 shapes cannot be multiplied (1x1353200 and 162400x1024)
Closing remaining open files:real_data_gen/fold0/label_test.h5...donereal_data_gen/fold0/test_test.h5...donereal_data_gen/fold0/code_test.h5...done
